#!/bin/bash

target=$1
address="http://nowhere"

case "${target}" in 
    "gateway") echo "target gateway"
               address="http://localhost:52051"
    ;;
    "envoy") echo "target gateway"
               address="http://localhost:51051"
    ;;
    *) echo "Invalid target: \"${target}\""
       echo "Usage: sh $0 [gateway|envoy]"
       exit 1
    ;;
esac

curl -X POST -d '{"name": "world", "sub": {"id": 123, "text": "supergui"}}' ${address}/v1/sayhello


## `buf-curl` supports direct communication with gRPC server.
## Use `--schema` to specify the protos.
## `buf-curl` default is using protocol `connectrpc`, use `--protocol grpc` to use gRPC compatible wires.
# buf curl -v --protocol grpc --http2-prior-knowledge --schema proto --data '{"name": "helloworld"}' http://127.0.0.1:50051/helloworld.v1.GreeterService/SayHello

# grpcurl -protoset ./config/envoy/helloworld.pb -plaintext -d '{"name": "hello"}' 127.0.0.1:50051 helloworld.v1.GreeterService/SayHello
