#!/bin/bash

sudo docker run -p 9901:9901 \
        -p 51051:51051 \
        -it --rm \
        -v ${PWD}/config/envoy/:/etc/envoy/ \
        envoyproxy/envoy:v1.29.0 \
        -c /etc/envoy/envoy.yaml \
        --log-level debug
